trigger: none  

pr: none      

resources:
  pipelines:
    - pipeline: triggeringPipeline  
      source: 'project-name/pipeline-name'  
      trigger: true                 

stages:
- stage: CheckoutAndBuild
  jobs:
  - job: CheckoutAndSetup
    steps:
    - checkout: self
      path: specific/path/for/checkout
      fetchDepth: 0 
      clean: true  
      ref: refs/heads/your-branch-name

