trigger:
  branches:
    include:
      - main

resources:
  pipelines:
    - pipeline: toolsPipeline
      source: tools-pipeline-name  

stages:
  - stage: CallToolsPipeline
    displayName: Trigger Tools Pipeline
    jobs:
      - job: TriggerTools
        displayName: Trigger Tools Repository Checkout
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: toolsPipeline
