name: CI/CD Pipeline

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        run: echo "branch_name=${GITHUB_REF}" >> $GITHUB_ENV

  check_branch_and_tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check if valid branch and tag for sit
        if: inputs.environment == 'sit'
        run: | 
          if [[ "${{ env.branch_name }}" != "refs/heads/main" && ! "${{ env.branch_name }}" =~ ^refs/heads/release/ ]]; then 
            echo "Error: Only the main or release branches can trigger sit environments."
            exit 1
          fi

          if [ "${{ github.ref_type }}" != "tag" ]; then
            echo "Error: A tag is required to trigger sit environments."
            exit 1
          fi
        shell: bash

